{% set name = "nbdime" %}
{% set version = "0.1.1" %}
{% set sha256 = "39ff9ded0e0db77d3083363dc50d923524ad4a14a1ef59fc59fed50da42cf635" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - nbformat
    - six
    - colorama
    - tornado
    - requests
    - backports.shutil_which

test:
  imports:
    - nbdime
  commands:
    - nbdime show -h

about:
  home: https://nbdime.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: 'Diff and merge of Jupyter Notebooks'
  doc_url: https://nbdime.readthedocs.io/
  dev_url: https://github.com/jupyter/nbdime

extra:
  recipe-maintainers:
    - kain88-de
    - minrk
