{% set version = "2.1.0" %}

package:
  name: nbdime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbdime/nbdime-{{ version }}.tar.gz
  sha256: 4e3efdcfda31c3074cb565cd8e76e2e5421b1c4560c3a00c56f8679dd15590e5

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
    - jupyter nbextension install --sys-prefix --py nbdime
  entry_points:
    - nbdime=nbdime.__main__:main_dispatch
    - nbshow=nbdime.nbshowapp:main
    - nbdiff=nbdime.nbdiffapp:main
    - nbdiff-web=nbdime.webapp.nbdiffweb:main
    - nbmerge=nbdime.nbmergeapp:main
    - nbmerge-web=nbdime.webapp.nbmergeweb:main
    - git-nbdiffdriver=nbdime.vcs.git.diffdriver:main
    - git-nbdifftool=nbdime.vcs.git.difftool:main
    - git-nbmergedriver=nbdime.vcs.git.mergedriver:main
    - git-nbmergetool=nbdime.vcs.git.mergetool:main
    - hg-nbdiff=nbdime.vcs.hg.diff:main
    - hg-nbdiffweb=nbdime.vcs.hg.diffweb:main
    - hg-nbmerge=nbdime.vcs.hg.merge:main
    - hg-nbmergeweb=nbdime.vcs.hg.mergeweb:main

requirements:
  host:
    - python >=3.6
    - pip
    - colorama
    - notebook
  run:
    - python >=3.6
    - colorama
    - gitpython !=2.1.4,!=2.1.5,!=2.1.6
    - jinja2 >=2.9
    - nbformat
    - notebook
    - pygments
    - requests
    - six
    - tornado

test:
  requires:
    - pip
  imports:
    - nbdime
    - nbdime.diffing
  commands:
    - pip check
    - nbdime show -h
    - nbshow -h
    - nbdiff -h
    - nbdiff-web -h
    - nbmerge -h
    - nbmerge-web -h
    - git-nbdifftool -h
    - git-nbmergetool -h
    - git-nbdiffdriver -h
    - git-nbmergedriver -h
    - hg-nbdiff -h
    - hg-nbdiffweb -h
    - hg-nbmerge -h
    - hg-nbmergeweb -h

about:
  home: https://nbdime.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Diff and merge of Jupyter Notebooks
  doc_url: https://nbdime.readthedocs.io/
  dev_url: https://github.com/jupyter/nbdime

extra:
  recipe-maintainers:
    - kain88-de
    - minrk
    - ocefpaf
