{% set name = "nbdime" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62ab50a758282523c4501144b9f314221dbbaed0403c12fd70f6a4fcc532ec24

build:
  number: 0
  skip: true  # [py<36]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - git-nbdiffdriver = nbdime.vcs.git.diffdriver:main
    - git-nbdifftool = nbdime.vcs.git.difftool:main
    - git-nbmergedriver = nbdime.vcs.git.mergedriver:main
    - git-nbmergetool = nbdime.vcs.git.mergetool:main
    - hg-nbdiff = nbdime.vcs.hg.diff:main
    - hg-nbdiffweb = nbdime.vcs.hg.diffweb:main
    - hg-nbmerge = nbdime.vcs.hg.merge:main
    - hg-nbmergeweb = nbdime.vcs.hg.mergeweb:main
    - nbdiff = nbdime.nbdiffapp:main
    - nbdiff-web = nbdime.webapp.nbdiffweb:main
    - nbdime = nbdime.__main__:main_dispatch
    - nbmerge = nbdime.nbmergeapp:main
    - nbmerge-web = nbdime.webapp.nbmergeweb:main
    - nbshow = nbdime.nbshowapp:main

requirements:
  host:
    - pip
    - python
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-jupyter-builder >=0.5
  run:
    - python
    - nbformat
    - colorama
    - pygments
    - tornado
    - requests
    - gitpython !=2.1.4,!=2.1.5,!=2.1.6
    - jupyter_server
    - jupyter-server-mathjax >=0.2.2
    - jinja2 >=2.9

# ConnectionRefusedError: [Errno 111] Connection refused
{% set tests_to_skip = "test_diff_api_checkpoint" %}
# FileNotFoundError: [Errno 2] No such file or directory: 'git'
{% set tests_to_skip = tests_to_skip + " or test_nbmerge_app_decisions_outfile" %}
{% set tests_to_skip = tests_to_skip + " or test_interrogate_filter_no_repo" %}
{% set tests_to_skip = tests_to_skip + " or test_filter_cmd_invalid_filter" %}
{% set tests_to_skip = tests_to_skip + " or test_apply_filter_no_repo" %}
# AssertionError: assert ['<<<<<<< loc...\nto align\n'] == ['<<<<<<< loc...>>>>> remote']
{% set tests_to_skip = tests_to_skip + " or test_merge_input_strategy_inline_source_conflict" %}
# AssertionError: assert {'nbformat': ...utputs': []}]} == {'nbformat': ...utputs': []}]}
{% set tests_to_skip = tests_to_skip + " or test_inline_merge_source_replace_line" %}
{% set tests_to_skip = tests_to_skip + " or test_inline_merge_source_add_to_line" %}
{% set tests_to_skip = tests_to_skip + " or test_inline_merge_source_patches_both_ends" %}
{% set tests_to_skip = tests_to_skip + " or test_inline_merge_cells_insertion_similar" %}
{% set tests_to_skip = tests_to_skip + " or test_inline_merge_cells_replacement_similar" %}

test:
  source_files:
    - nbdime/tests
    - nbdime/vcs/git
  imports:
    - nbdime
    - nbdime.args
    - nbdime.config
    - nbdime.diff_format
    - nbdime.diff_utils
    - nbdime.diffing
    - nbdime.diffing.config
    - nbdime.diffing.directorydiff
    - nbdime.diffing.lcs
    - nbdime.diffing.notebooks
    - nbdime.diffing.seq_bruteforce
    - nbdime.diffing.seq_difflib
    - nbdime.diffing.sequences
    - nbdime.diffing.snakes
    - nbdime.log
    - nbdime.merging.decisions
    - nbdime.merging.generic
    - nbdime.merging.notebooks
    - nbdime.merging.strategies
    - nbdime.nbdiffapp
    - nbdime.nbmergeapp
    - nbdime.nbshowapp
    - nbdime.prettyprint
    - nbdime.profiling
    - nbdime.utils
    - nbdime.vcs.git
    - nbdime.vcs.git.diffdriver
    - nbdime.vcs.git.filter_integration
    - nbdime.vcs.hg
    - nbdime.vcs.hg.diff
    - nbdime.vcs.hg.diffweb
    - nbdime.webapp
    - nbdime.webapp.nbdiffweb
    - nbdime.webapp.nbmergeweb
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Few files of Windows tests failing (Tests related to Git). Cannot exclude them when I use '--pyargs nbdime', '--ignore' flag doesn't work.
    - pytest -v -k "not ({{ tests_to_skip }})" --pyargs nbdime  # [unix]
    - nbdime show -h
    - nbshow -h
    - nbdiff -h
    - nbdiff-web -h
    - nbmerge -h
    - nbmerge-web -h
    - git-nbdifftool -h
    - git-nbmergetool -h
    - git-nbdiffdriver -h
    - git-nbmergedriver -h
    - hg-nbdiff -h
    - hg-nbdiffweb -h
    - hg-nbmerge -h
    - hg-nbmergeweb -h
    # print them all for debugging
    - jupyter labextension list
    - jupyter server extension list
    # write out lists to grep
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    # check files
    - grep -iE "nbdime-jupyterlab.*OK*" labextensions
    - grep -iE "nbdime.*OK" server_extensions
  requires:
    - jupyterlab>=4.0.0,<5
    - m2-grep  # [win]
    - pip
    - tabulate
    - jsonschema
    # pytest<8 to fix: test_web.py: 'yield' keyword is allowed in fixtures, but not in tests (test_fetch_diff)
    - pytest >=6.0,<8

about:
  home: https://nbdime.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.md
    - nbdime/labextension/static/third-party-licenses.json
  summary: Diff and merge of Jupyter Notebooks
  description: |
    nbdime provides “content-aware” diffing and merging of Jupyter notebooks. 
    It understands the structure of notebook documents. 
    Therefore, it can make intelligent decisions when diffing and merging notebooks.
  doc_url: https://nbdime.readthedocs.io
  dev_url: https://github.com/jupyter/nbdime

extra:
  recipe-maintainers:
    - kain88-de
    - minrk
    - ocefpaf
    - bollwyvl