travis:
  secure:
    BINSTAR_TOKEN: FWX963dLxMuTWQ1K457R5Ey3JgMnmUO+i5Tjs2w3n/xzZ5S9EhPhpw4AX2op1uL5pS53BXFwT+jIuJMz9n6+cKFuUYOxH6gWur6YZxXkFz2jnjOE7bl3pQeRISBwIXVscyfBCwGswwPklMg44M6mMe7IOWMbia/GrFXxJABinc5AVHAUWSdTgYcfChFHbVSW2jdFSqAM70Cqn2tx74COFf+rUrVeHijhzAaLhS36U4SG5kolyty/jVD41OAceADRVzJffdd6KLMmY186RcKtrSPYg2e43i5tP5LZedkJrVuBVN78NrJrMvXlVJ/nBIBOXCJrXCBVoHAAG5xcLtvBdWkiCjqtseL79pLkEOonPUHLeiNca8Kl5r1IBp7XmJIDS4JcTjyRFkYDwbi3/VdpBzeg1Lk5/9+VUvQeD1Bbirpxbu967E+3eeVXUCLs6F7vU1HqwWSQGHzx9hHrjDU8v6cGspt80nhKOWGVMGdX2LwpHH0urDIU7XXDDLmA/TwHCaflu2CzKZLzmGiOxaLh7MysldmDgV4/TAdcHzqQm6HxU1JzvTdIGKkEyrEcF42eq3+DgWQAgETdQdUrRtlp3iFYjldXQ2kUNJJAeNizGDTK/BAQuhpTDBqVKCGZ+DnhWDQEUnRiKSfCWLXRrf/0qadoJjtx8lBbJAxhKAOHwcU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
