travis:
  secure:
    BINSTAR_TOKEN: SxivwPbnkSauEVuKwUGdO7fxwZ9K0zL833+VB/acshV+j4Om9d4mw12xjdyMA1m1NU2PqZI8udA0Hy4Ybt58VkBcKKPIYJVJxX6pj+dzpWAkVfSwdNMW3dTGPXJR5dCQa7AQ6iBkLl+oz3vehWoe/IQGD4FEMtQ9gqqc1wPxPbKSWJzFNM7GPlSWaBtyRFhsWeumHbn9Cy9/n0DlKL+XrYBjekyY3WEwaHyli1mhpEnvU60k2NCd6Hpz6csaVAgA9JXpeIxe/dx+ZWAyvJiMaqPMakHIHPgWiTCBq2rYDfZ+BJR0MMp0NjkUxdxWGCMrNJxLPiF6BiABwEm/dsVqou3DvFtPvXq9T/wbWjU/FtpxZ8bgXHUU8Y91IlFKuCYKfX44XZA06UDILx6kXMnuoWRCAAJ0Hzt5dr9Sn3zHKmaqlUceDTJRDq1+MJjFiO8Qxt/pTU/2OWzPNkT8kxWjBorYCOMjypem+5FbYo9We6uVPDe+Ru/5FZBmrEqL5enIz2Tc+i1Pcubl2NvpnYQ1/3JiFJ7g45O0PgpjzDjAzCiPWLepBHPLTUO6DDwgVOKHg6/weyfZngi642Y9DjS1xS0hEa/fTcJhd2h9oB03CP1DJj6xHuZmSKo0nWOjdFHRN78EJ9CIK430zMGgvN8KdyvYcWASm8Zye34qkjA0PUk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
