appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: AdkQP6E/N+Oxk2ZE30vsGhxGs6UdzsNhcyFPnnQjZbxCvHBb0nuqs3DjcP+cenn6N5Ig/60DDu6uvZmedoolzOTA6X++bbjfc2WmDEMrHOGV/XQFWwG3K/3DmXD45n1xMEWIyYCsjdwEeqhBMGCPQNrIE0XvptrpKbptRLnwOQqz0epBuPtV/xvLkuII7TI0zzOHg/+UKfQlXYNmbxBtVUsK9lACQj2wQKm7q8FSLUT/hDXNfpKxAJddlAtyoGNEDoGfESgPOG5fsYAVsT7j9wnc5u0zhadWabx1AWo6aX4T9CGV2WJD/ZqXjGb0756pv+tkwLDoj/BlhqL0qfdg6i/m9pHvuj72ftDtEyp6wUO7Lz+SdLDlZsHAL1qIDH0TLu5Y5Jofi8J0IDXk2RGDUZ7U24+Zxyretvrrnl3Cf93AdwOED6fDs2xSPV5X+LEVxYhNgHQTXB5l8annRwnuuujF+BKyJFz/dqh8ctNofE/A3DtLad2h7tUU7+pzYAIErhkmeQJg6CbqXTMy7Ai8S1kmjCSigwQhpXlOPpWE1+lqQEaMJqnnaV8x2ZhzK3khxW7xp0ujr1U/L1qfufHVILrNmmygHBzhiwlCAzr+Dl21TqLioH5uD0IoSFNTaLMCjXIR/ntoGYtoDI0ZFo/gbgm9toOHzxOYwgeBqpcIvL0=}
provider:
  win: azure
conda_forge_output_validation: true
